url: https://aptanadev.github.io
baseurl: "/juragandana/"
# Site settings
title: JURAGAN DANA
email: Cair@juragandana.com
description: "Juragan Dana adalah platform yang mempertemukan pemodal dan pelanggan. Menyediakan pinjaman struktur fleksibel, proses sangat cepat dan mudah, bekerja sama dengan lebih dari 15 pemodal. Sehingga nasabah dapat dengan mudah mengakses dana tunai dengan suku bunga yang menguntungkan serta jangka waktu pembayaran yang fleksibel, baik untuk pembiayaan ulang kendaraan bermotor maupun pembiayaan perumahan."

# Team names, titles and social links
people:
  - name: Kay Garland
    pic: 1
    position: Lead Designer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: stack-overflow
        url: #

  - name: Larry Parker
    pic: 2
    position: Lead Marketer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: linkedin
        url: #

  - name: Diana Petersen
    pic: 3
    position: Lead Developer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: google-plus
        url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://web.facebook.com/profile.php?id=61558396452307
  - title: instagram
    url: https://www.instagram.com/muf_dana/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
